# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/Mwh.SampleCore.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/Mwh.SampleCore.sln'
    feedsToUse: 'select'


- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/Mwh.SampleCore.sln'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/Mwh.SampleCore.sln'


- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true